print ("Podaj imię:")
name = input()
print("Wpisane imię: ", name)
print ("Podaj nazwisko:")
surname = input()
print ("Podane nazwisko: ", surname)
print("Gdzie mieszkasz?")
city = input ()
print ("Podane miasto to: ", city)
print("Nazywasz się", name, surname, "i mieszkasz w miejscowości", city, ".")